// SPDX-License-Identifier: AGPL-3.0-only
import AppKit
import CliprillCore

public enum CapturedClipboardContent: Sendable {
    case text(String)
    case image(Data)
}

public enum ClipboardWrite: Sendable {
    case text(String)
    case image(png: Data, tiff: Data)

    public static func image(png: Data) throws -> ClipboardWrite {
        .image(png: png, tiff: try PreparedClipboardImage.tiff(fromPNG: png))
    }
    /// Works with named pasteboards too, so tests never replace the user's clipboard.
    @MainActor public func write(to pasteboard: NSPasteboard) throws {
        let item = NSPasteboardItem()
        let prepared: Bool
        switch self {
        case .text(let text): prepared = item.setString(text, forType: .string)
        case .image(let png, let tiff):
            prepared = item.setData(png, forType: .png) && item.setData(tiff, forType: .tiff)
        }
        guard prepared else { throw CoreError("clipboard", "Could not prepare clipboard content.") }
        pasteboard.clearContents()
        guard pasteboard.writeObjects([item]) else { throw CoreError("clipboard", "Could not write clipboard content.") }
    }
}

public enum ClipboardReader {
    @MainActor public static func read(from pasteboard: NSPasteboard, captureImages: Bool = true) -> CapturedClipboardContent? {
        let types = Set((pasteboard.types ?? []).map(\.rawValue))
        guard types.isDisjoint(with: ["org.nspasteboard.TransientType", "org.nspasteboard.ConcealedType",
                                     "org.nspasteboard.AutoGeneratedType", "com.agilebits.onepassword"]) else { return nil }
        // Browsers often supply an image and its URL together. Capture the actual image first.
        let imageTypes: [NSPasteboard.PasteboardType] = [.png, .tiff, .init("public.jpeg"), .init("public.heic"), .init("public.heif"), .init("com.compuserve.gif"), .init("com.microsoft.bmp"), .init("org.webmproject.webp")]
        if let type = pasteboard.availableType(from: imageTypes) {
            // Avoid loading a large image payload when image history is disabled.
            guard captureImages else { return nil }
            if let data = pasteboard.data(forType: type) { return .image(data) }
        }
        if let text = pasteboard.string(forType: .string) { return .text(text) }
        return nil
    }
}
